### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mxkay** [mxkay/forgotten-frontend#43]
We should write a professional README that contains instructions about how to spin up our app and contribute to this repo.

**Comment by mohammad523** [comment]
### **WELCOME to the Forgotten App's official repo!** 

In order to spin up our app there are a few steps you need to follow:

`
*PREREQUISITE - node.js*



- STEP 1 -  Install Expo CLI

`npm install -g expo-cli`



- STEP 2 - (OPTIONAL) MAC USERS

**[Install Watchman](https://facebook.github.io/watchman/docs/install#buildinstall)**



- STEP 3 - Clone down this repository!

`git clone https://github.com/mxkay/forgotten-frontend`



- STEP 4 - Install the node modules in the App's Folder!

`npm install
`


- STEP 5 - (RECOMMENDED) DOWNLOAD THE EXPO APP ON YOUR MOBILE DEVICE


[ANDROID](https://play.google.com/store/apps/details?id=host.exp.exponent&hl=en_US)

[IOS](https://apps.apple.com/us/app/expo-client/id982107779)



- STEP 6 - In the the App's folder run this code in your terminal:

`expo start`


- STEP 7 - Scan the barcode

A page will open up in your browser. There will be a few options. You could run the app in your browser, or you could scan 
the QR code with your mobile device's camera!
`scan the QR code`


- STEP 8 - Enjoy Using Our App and Leave Feedback!


`
